#cloud-config

---
hostname: master

ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7XpxdpfJOtHeni/zRBYX2bpjEQDxjfMwbpoGVs53p9Cql3+Jj3cIqN7Tb3DcrE0xPlV+mjcemu5zDDikcnyhpLkts07Jga0B3qHDa3yHY4E0GIFlkA8Ni/7fjlP5dtsfhb57USEy0k3Tt1/CJSsXIZA3TgwsiC4EDXxZ2vrvAFNbQz7q8XeoFPRpyL5nAEcUrBssO2pQrRRbb+RFL7BhjWqwPynukVtntGs8t42+691tymiMPjS1z/nHP4vsv84PhM1x2zmUFJGYYIuWmfTdqMUUUsWMvhP2kGq3rjINzSDY8PNkZm5iQ54SGSiggCP3c013x0uKWmvB0K1yoi+1X

write-files:
- path: /etc/conf.d/nfs
  permissions: '0644'
  content: |
    OPTS_RPC_MOUNTD=""

- path: /opt/bin/wupiao
  permissions: '0755'
  content: |
    #!/bin/bash
    # [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
    [ -n "$1" ] && \
      until curl -o /dev/null -sIf http://$${1}; do \
        sleep 1 && echo -n .;
      done;
    exit $?

- path: /opt/bin/wufae
  permissions: '0755'
  content: |
    #!/bin/bash
    # [w]ait [u]ntil [f]ile [a]ctually [e]xists
    while [ ! -f "$1" ]; do
      sleep 1 && echo -n .; done
    sleep 5

coreos:
  update:
    group: alpha
    reboot-strategy: off

  etcd2:
    name: master
    listen-client-urls: http://0.0.0.0:2379
    advertise-client-urls: http://$private_ipv4:2379
    initial-cluster-token: k8s_etcd
    listen-peer-urls: http://$private_ipv4:2380
    initial-advertise-peer-urls: http://$private_ipv4:2380
    initial-cluster: master=http://$private_ipv4:2380
    initial-cluster-state: new

  fleet:
    metadata: role=master

  units:
  - name: bootstrap-master.service
    command: start
    content: |
      [Unit]
      Description=Bootstrap the OpenShift master
      Requires=network-online.target
      After=network-online.target

      [Service]
      # Setup network environment
      ExecStartPre=/opt/bin/wufae /opt/bin/setup-network-environment
      ExecStartPre=/usr/bin/chown root:root /opt/bin/setup-network-environment
      ExecStartPre=/usr/bin/chmod +x /opt/bin/setup-network-environment
      ExecStartPre=/opt/bin/setup-network-environment
      # Generate OpenShift master configurations
      ExecStartPre=/opt/bin/wufae /opt/bin/openshift
      ExecStartPre=/usr/bin/chown root:root /opt/bin/openshift
      ExecStartPre=/usr/bin/chmod +x /opt/bin/openshift
      ExecStartPre=/usr/bin/ln -s /opt/bin/openshift /opt/bin/oadm
      ExecStart=/opt/bin/openshift start master \
      --write-config=${OSCONFIG}/master/ \
      --listen=https://0.0.0.0:8443 \
      --master=https://$private_ipv4:8443 \
      --public-master=https://$public_ipv4:8443 \
      --dns=tcp://$private_ipv4:53 \
      --etcd=http://$private_ipv4:2379
      # Copy files for nodes
      ExecStartPost=/usr/bin/chmod +r ${OSCONFIG}/master/admin.kubeconfig
      ExecStartPost=/usr/bin/chmod +r ${OSCONFIG}/master/openshift-registry.kubeconfig
      ExecStartPost=/usr/bin/sleep 5
      ExecStartPost=/usr/bin/cp -R ${OSCONFIG}/master ${HOME}/
      ExecStartPost=/usr/bin/chown -R core:core ${HOME}/master/
      # Setup for CLI
      ExecStartPost=/usr/bin/rm ${HOME}/.bashrc
      ExecStartPost=/usr/bin/mv /opt/bin/.bashrc ${HOME}/.bashrc
      ExecStartPost=/usr/bin/chown core:core ${HOME}/.bashrc
      RemainAfterExit=yes
      Type=oneshot

  - name: fleet.service
    command: start

  - name: docker.service
    command: start

  - name: openshift-master.service
    command: start
    content: |
      [Unit]
      Description=OpenShift Master
      Documentation=https://github.com/openshift/origin
      Requires=bootstrap-master.service etcd2.service
      After=bootstrap-master.service etcd2.service

      [Service]
      EnvironmentFile=/etc/network-environment
      ExecStartPre=/opt/bin/wupiao 127.0.0.1:2379/v2/machines
      ExecStart=/opt/bin/openshift start master \
      --config=${OSCONFIG}/master/master-config.yaml
      Restart=always
      RestartSec=10
