# https://hekad.readthedocs.org/en/dev/config/filters/http_status.html
#[HttpStatus]
#  type = 'SandboxFilter'
#  filename = 'lua_filters/http_status.lua'
#  ticker_interval = 60
#  preserve_data = true
#  message_matcher = "Logger == 'nginx.access' && Type == 'fxa-auth-server'"
#  [HttpStatus.config]
#    sec_per_row = 60
#    rows = 1440
#    anomaly_config = "roc(\"HTTP Status\", 2, 15, 0, 1.5, true, false) roc(\"HTTP Status\", 4, 15, 0, 1.5, true, false) mww_nonparametric(\"HTTP Status\", 5, 15, 10, 0.8)"
#    alert_throttle = 300
#    preservation_version = 0
