apiVersion: v1
kind: List
items:
-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: registry
-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: router
-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: heapster
