apiVersion: v1
kind: List
items:
-
  apiVersion: v1
  kind: SecurityContextConstraints
  metadata:
    name: restricted
  allowHostDirVolumePlugin: true
  allowPrivilegedContainer: true
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: MustRunAs
  groups:
  - system:authenticated
-
  apiVersion: v1
  kind: SecurityContextConstraints
  metadata:
    name: privileged
  allowHostDirVolumePlugin: true
  allowHostNetwork: true
  allowHostPorts: true
  allowPrivilegedContainer: true
  allowedCapabilities: null
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: RunAsAny
  groups:
  - system:cluster-admins
  - system:nodes
  users:
  - system:serviceaccount:openshift-infra:build-controller
  - system:serviceaccount:default:router
-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: registry
-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: router
-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: heapster
