#!/bin/bash

#oc policy add-role-to-user admin admin -n gf-project
#oc policy add-role-to-user cluster-admin admin 

# Delete all components of Gasista Felice application
oc delete all -l app=gf

# Create a new application of Gasista Felice
oc new-app -f gasistafelice.yaml \
  -p SERVER_NAME=gf.${BASE_DOMAIN}

# Watch pods in real-time
./watch_pods

# Load the test data
oc exec $(oc get pods | grep back | awk '{print $1}') -- psql -f /code/gasistafelice/fixtures/test.sql
