#!/bin/bash

#oc policy add-role-to-user admin admin -n gf-project
#oc policy add-role-to-user cluster-admin admin 

oc delete all -l app=gf
oc new-app -f gasistafelice.yaml \
  -p SERVER_NAME=gf.${BASE_DOMAIN}
./watch

# Provide the test database
oc exec $(oc get pods | grep back | awk '{print $1}') -- psql -f /code/gasistafelice/fixtures/test.sql
