#!/bin/bash
# https://docs.openshift.org/latest/admin_guide/cluster_metrics.html

oadm policy add-cluster-role-to-user \
  cluster-reader \
  system:serviceaccount:default:heapster

oc new-app -f monitoring.yaml \
  -p SERVER_NAME=${BASE_DOMAIN}

./watch

# Logging
# https://docs.openshift.org/latest/admin_guide/aggregate_logging.html
# http://kubernetes.io/v1.0/docs/user-guide/logging.html
# http://kubernetes.io/v1.0/docs/getting-started-guides/logging-elasticsearch.html
