#!/bin/bash

# Delete all components of Monitoring Stack
oc delete all -l app=monit

# Create a new Monitoring Stack
oc new-app -f monitoring.yaml \
  -p BASE_DOMAIN=${BASE_DOMAIN},NODES=${NODES}

# Watch pods in real-time
./watch_pods
