#!/bin/bash

oadm policy add-cluster-role-to-user \
  cluster-reader \
  system:serviceaccount:default:heapster

oc delete all -l app=monit
oc new-app -f monitoring.yaml \
  -p BASE_DOMAIN=${BASE_DOMAIN},NODES=${NODES}

./watch
