allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities: null
apiVersion: v1
groups:
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  creationTimestamp: 2015-08-15T13:46:09Z
  name: privileged
  resourceVersion: "61"
  selfLink: /api/v1/securitycontextconstraints/privileged
  uid: fc2f9a10-4353-11e5-b45c-040164d47001
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:build-controller
- system:serviceaccount:default:router
