#!/bin/bash
# https://docs.openshift.org/latest/admin_guide/install/deploy_router.html
# https://docs.openshift.org/latest/architecture/core_concepts/routes.html
# http://blog.kubernetes.io/2015/07/strong-simple-ssl-for-kubernetes.html

oadm router ex-router \
  --replicas=1 \
  --credentials=${KUBECONFIG} \
  --service-account=router
