#!/bin/bash
# https://docs.openshift.org/latest/admin_guide/install/deploy_router.html
# https://docs.openshift.org/latest/architecture/core_concepts/routes.html
# http://blog.kubernetes.io/2015/07/strong-simple-ssl-for-kubernetes.html

echo
echo 'at the end, append the following line: '
echo '- system:serviceaccount:default:router'
echo
oc edit scc privileged
oadm router ex-router \
  --replicas=1 \
  --credentials=${KUBECONFIG} \
  --service-account=router
